const API=window.KAYSTANT_API||'';
const token=()=>localStorage.getItem('kaystant_token')||'';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let posts=[];
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function authHeaders(){return {'Content-Type':'application/json','Authorization':`Bearer ${token()}`}}
function render(list=posts){const box=$('#post-list');if(!box)return;box.innerHTML=list.map((p,i)=>`<article class="post" data-id="${p.id||''}"><div class="post-avatar" style="background:${p.color||'#5367d8'}">${p.initial||'A'}</div><div class="post-copy"><div class="post-meta"><a href="profile.html?user=${encodeURIComponent(p.user)}">@${p.user}</a> · ${p.type} ${p.user!=='morveyn'?`<button class="follow-btn" data-follow="${p.user}">seguir</button>`:''}</div><h3>${p.title}</h3><p>${p.body}</p><div class="post-meta">${p.tints||0} tintas recebidas · agora</div></div><div class="post-actions"><div class="ink-meter" style="--post-color:${p.color||'#5367d8'};--fill:${p.fill||0}%"><i></i></div><span class="ink-label">${p.fill||0}%</span>${p.id?`<button class="ink-btn" data-ink="${p.id}" title="Deixar tinta">+ tinta</button>`:''}</div></article>`).join('');
 $$('.ink-btn').forEach(b=>b.onclick=()=>giveInk(b.dataset.ink,b));$$('.follow-btn').forEach(b=>b.onclick=()=>followAuthor(b.dataset.follow,b));}
async function followAuthor(name,button){if(!token()){toast('Entre para seguir autores ✦');$('#auth-modal')?.showModal();return}button.disabled=true;try{const r=await fetch(`${API}/users/${encodeURIComponent(name)}/follow`,{method:'POST',headers:authHeaders()});if(!r.ok)throw Error();const d=await r.json();button.textContent=d.following?'seguindo':'seguir';toast(d.following?`Você está seguindo @${name} ✦`:`Você deixou de seguir @${name}`)}catch(e){toast('Não foi possível atualizar agora.')}button.disabled=false}
async function loadFeed(){if(!API)return;try{const r=await fetch(API+'/feed');if(r.ok){const data=await r.json();if(data.length){posts=data.map(x=>({id:x.id,user:x.author?.username||'autor',initial:(x.author?.username||'A')[0].toUpperCase(),title:x.title,type:x.category==='poesia'?'Poesia':x.category==='artigo_cientifico'?'Artigo científico':'Estudo/Pesquisa',body:x.body,color:x.author?.ink_color,fill:x.fill,tints:x.ink_total}));render();}}}catch(e){}}
async function giveInk(id,button){if(!token()){toast('Entre para deixar tinta ✦');$('#auth-modal')?.showModal();return}button.disabled=true;try{const r=await fetch(`${API}/posts/${id}/ink`,{method:'POST',headers:authHeaders(),body:JSON.stringify({amount:1})});if(!r.ok)throw Error();const p=await r.json();const local=posts.find(x=>x.id===id);if(local){local.fill=p.fill;local.tints=p.ink_total;}$(`[data-id="${id}"]`)?.querySelector('.ink-label').textContent=`${p.fill}%`;toast('Sua tinta foi deixada ✦');}catch(e){toast('Essa postagem já recebeu sua tinta ou você precisa entrar.')}button.disabled=false;}
function open(d){d?.showModal()}
$('#write-now')?.addEventListener('click',()=>open($('#write-modal')));
async function openProfile(){if(!token()){open($('#auth-modal'));return}try{const r=await fetch(API+'/me',{headers:authHeaders()});if(!r.ok)throw Error();const u=await r.json();$('#profile-display').value=u.display_name||'';$('#profile-username').value=u.username||'';$('#profile-bio').value=u.bio||'';$('#profile-color').value=u.ink_color||'#5367d8';document.documentElement.style.setProperty('--ink',u.ink_color||'#5367d8');open($('#profile-modal'))}catch(e){toast('Não foi possível carregar seu perfil.')}}
$('#open-profile')?.addEventListener('click',e=>{e.preventDefault();openProfile()});
$('#open-profile2')?.addEventListener('click',e=>{e.preventDefault();openProfile()});
let signup=false;$('#signup-mode')?.addEventListener('click',()=>{signup=!signup;$('#confirm-wrap').hidden=!signup;$('#auth-submit').textContent=signup?'Criar conta':'Entrar'});$('#auth-submit')?.addEventListener('click',async e=>{e.preventDefault();const email=$('#auth-email').value,password=$('#auth-password').value;if(signup&&password!==$('#auth-confirm').value){toast('As senhas precisam ser iguais.');return}try{const r=await fetch(API+(signup?'/auth/signup':'/auth/login'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,...(signup?{username:email.split('@')[0]}:{})})});if(!r.ok)throw Error();const d=await r.json();localStorage.setItem('kaystant_token',d.token);toast(signup?'Conta criada ✦':'Você voltou para o Kaystant ✦');$('#auth-modal').close();location.reload()}catch(e){toast(signup?'E-mail ou username já usado.':'Confira seu e-mail e sua senha.')}});if(token()&&$('#logout')){$('#logout').hidden=false;$('#logout').onclick=()=>{localStorage.removeItem('kaystant_token');location.reload()}}
/* As cores da tinta são persistidas por home-fix.js via API. */
$$('.palette button').forEach(b=>b.onclick=()=>{document.documentElement.style.setProperty('--ink',b.dataset.color);$('#profile-color')?.setAttribute('value',b.dataset.color)});
$('#profile-save')?.addEventListener('click',async e=>{e.preventDefault();if(!token())return;const body={display_name:$('#profile-display')?.value.trim(),username:$('#profile-username')?.value.trim(),bio:$('#profile-bio')?.value,ink_color:$('#profile-color')?.value};try{const r=await fetch(API+'/profile',{method:'PATCH',headers:authHeaders(),body:JSON.stringify(body)});if(!r.ok)throw Error();toast('Perfil salvo de verdade ✦');$('#profile-modal').close()}catch(e){toast('Não foi possível salvar agora.')}});
$('#publish')?.addEventListener('click',async e=>{e.preventDefault();if(!token()){toast('Entre para publicar ✦');return}const category={'Poesia':'poesia','Artigo científico':'artigo_cientifico','Estudo/Pesquisa':'estudo_pesquisa'}[$('#new-type')?.value||'Poesia'];try{const r=await fetch(API+'/posts',{method:'POST',headers:authHeaders(),body:JSON.stringify({title:$('#new-title').value,body:$('#new-body').value,category})});if(!r.ok)throw Error();toast('Publicação criada e pronta para receber tinta ✦');$('#write-modal').close();loadFeed()}catch(e){toast('Entre e preencha título e texto para publicar.')}});
$('#filter')?.addEventListener('change',e=>{const v=e.target.value;render(v==='Poesias'?posts.filter(p=>p.type==='Poesia'):v==='Estudos e pesquisas'?posts.filter(p=>p.type!=='Poesia'):posts)});
$$('.buy').forEach(b=>b.onclick=()=>toast('A compra será ligada à carteira na próxima atualização ✦'));
if(token()){if($('#header-label'))$('#header-label').textContent='Minha conta';fetch(API+'/me',{headers:{Authorization:`Bearer ${token()}`}}).then(r=>r.ok?r.json():null).then(u=>{if(u){$('#header-label').textContent='@'+u.username;$('#header-coins').hidden=false;$('#header-coins').textContent=u.coins+' ◈';$('#header-avatar').textContent=(u.username||'K')[0].toUpperCase()}}).catch(()=>{})}render();loadFeed();
