const API=window.KAYSTANT_API||'';
const token=()=>localStorage.getItem('kaystant_token')||'';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fallback=[
 {user:'lua_de_papel',initial:'L',title:'A cidade depois da chuva',type:'Poesia',body:'Há lugares que só aparecem quando o barulho termina. Escrevi este para quem aprendeu a escutar o intervalo.',color:'#e97768',fill:72,tints:38},
 {user:'caderno.do.mar',initial:'C',title:'Sobre insistir nas primeiras tentativas',type:'Estudo/Pesquisa',body:'Uma pequena pesquisa sobre o que acontece quando deixamos de tratar o rascunho como fracasso.',color:'#5367d8',fill:49,tints:24},
 {user:'raiz_e_ensaio',initial:'R',title:'O que a leitura devolve',type:'Artigo científico',body:'Notas sobre memória, formação de repertório e os mundos que se abrem quando lemos devagar.',color:'#79a86d',fill:88,tints:57}
];
let posts=[...fallback];
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function authHeaders(){return {'Content-Type':'application/json','Authorization':`Bearer ${token()}`}}
function render(list=posts){const box=$('#post-list');if(!box)return;box.innerHTML=list.map((p,i)=>`<article class="post" data-id="${p.id||''}"><div class="post-avatar" style="background:${p.color||'#5367d8'}">${p.initial||'A'}</div><div class="post-copy"><div class="post-meta"><a href="profile.html?user=${encodeURIComponent(p.user)}">@${p.user}</a> · ${p.type}</div><h3>${p.title}</h3><p>${p.body}</p><div class="post-meta">${p.tints||0} tintas recebidas · agora</div></div><div class="post-actions"><div class="ink-meter" style="--post-color:${p.color||'#5367d8'};--fill:${p.fill||0}%"><i></i></div><span class="ink-label">${p.fill||0}%</span>${p.id?`<button class="ink-btn" data-ink="${p.id}" title="Deixar tinta">+ tinta</button>`:''}</div></article>`).join('');
 $$('.ink-btn').forEach(b=>b.onclick=()=>giveInk(b.dataset.ink,b));}
async function loadFeed(){if(!API)return;try{const r=await fetch(API+'/feed');if(r.ok){const data=await r.json();if(data.length){posts=data.map(x=>({id:x.id,user:x.author?.username||'autor',initial:(x.author?.username||'A')[0].toUpperCase(),title:x.title,type:x.category==='poesia'?'Poesia':x.category==='artigo_cientifico'?'Artigo científico':'Estudo/Pesquisa',body:x.body,color:x.author?.ink_color,fill:x.fill,tints:x.ink_total}));render();}}}catch(e){}}
async function giveInk(id,button){if(!token()){toast('Entre para deixar tinta ✦');$('#auth-modal')?.showModal();return}button.disabled=true;try{const r=await fetch(`${API}/posts/${id}/ink`,{method:'POST',headers:authHeaders(),body:JSON.stringify({amount:1})});if(!r.ok)throw Error();const p=await r.json();const local=posts.find(x=>x.id===id);if(local){local.fill=p.fill;local.tints=p.ink_total;}$(`[data-id="${id}"]`)?.querySelector('.ink-label').textContent=`${p.fill}%`;toast('Sua tinta foi deixada ✦');}catch(e){toast('Essa postagem já recebeu sua tinta ou você precisa entrar.')}button.disabled=false;}
function open(d){d?.showModal()}
$('#write-now')?.addEventListener('click',()=>open($('#write-modal')));
$('#open-profile')?.addEventListener('click',()=>token()?open($('#profile-modal')):open($('#auth-modal')));
$('#open-profile2')?.addEventListener('click',()=>token()?open($('#profile-modal')):open($('#auth-modal')));
$('#pet-edit')?.addEventListener('click',()=>toast('A personalização do pet chega na próxima camada ✦'));
$('#auth-submit')?.addEventListener('click',async e=>{e.preventDefault();try{const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('#auth-email').value,password:$('#auth-password').value})});if(!r.ok)throw Error();const d=await r.json();localStorage.setItem('kaystant_token',d.token);toast('Você voltou para o Kaystant ✦');$('#auth-modal').close();location.reload()}catch(e){toast('Confira seu e-mail e sua senha.')}});
$$('.dot').forEach(b=>b.onclick=()=>{document.documentElement.style.setProperty('--ink',b.dataset.color);$$('.dot').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast('Sua tinta mudou de cor ✦')});
$$('.palette button').forEach(b=>b.onclick=()=>{document.documentElement.style.setProperty('--ink',b.dataset.color);$('#profile-color')?.setAttribute('value',b.dataset.color)});
$('#profile-save')?.addEventListener('click',async e=>{e.preventDefault();if(!token())return;const body={bio:$('#profile-bio')?.value,ink_color:$('#profile-color')?.value};try{const r=await fetch(API+'/profile',{method:'PATCH',headers:authHeaders(),body:JSON.stringify(body)});if(!r.ok)throw Error();toast('Perfil salvo de verdade ✦');$('#profile-modal').close()}catch(e){toast('Não foi possível salvar agora.')}});
$('#publish')?.addEventListener('click',async e=>{e.preventDefault();if(!token()){toast('Entre para publicar ✦');return}const category={'Poesia':'poesia','Artigo científico':'artigo_cientifico','Estudo/Pesquisa':'estudo_pesquisa'}[$('#new-type')?.value||'Poesia'];try{const r=await fetch(API+'/posts',{method:'POST',headers:authHeaders(),body:JSON.stringify({title:$('#new-title').value,body:$('#new-body').value,category})});if(!r.ok)throw Error();toast('Publicação criada e pronta para receber tinta ✦');$('#write-modal').close();loadFeed()}catch(e){toast('Entre e preencha título e texto para publicar.')}});
$('#filter')?.addEventListener('change',e=>{const v=e.target.value;render(v==='Poesias'?posts.filter(p=>p.type==='Poesia'):v==='Estudos e pesquisas'?posts.filter(p=>p.type!=='Poesia'):posts)});
$('.pet-stage')?.addEventListener('click',()=>{const p=$('.pet');p.animate([{transform:'translateY(0)'},{transform:'translateY(-34px) rotate(12deg)'},{transform:'translateY(0)'}],{duration:650});toast('Pingo recebeu carinho ✦')});
$$('.buy').forEach(b=>b.onclick=()=>toast('A compra será ligada à carteira na próxima atualização ✦'));
render();loadFeed();
