-- Kaystant: isolated schema. It never touches kp_* tables used by KayePad.
create extension if not exists pgcrypto;
create table if not exists kt_users (id uuid primary key default gen_random_uuid(), email text unique not null, username text unique not null check(username ~ '^[A-Za-z0-9_.-]{3,40}$'), password_hash text not null, bio text not null default '', ink_color text not null default '#5367d8', coins integer not null default 0 check(coins >= 0), ink integer not null default 18 check(ink >= 0), badge text not null default 'normal', banner_url text not null default '', verified boolean not null default false, created_at timestamptz not null default now());
create table if not exists kt_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references kt_users(id) on delete cascade, token_hash text unique not null, expires_at timestamptz not null, revoked boolean not null default false);
create table if not exists kt_posts (id uuid primary key default gen_random_uuid(), user_id uuid not null references kt_users(id) on delete cascade, title text not null check(length(title) between 1 and 140), category text not null check(category in ('poesia','artigo_cientifico','estudo_pesquisa')), body text not null, ink_total integer not null default 0, ink_goal integer not null default 100 check(ink_goal between 20 and 1000), coins_awarded integer, redeemed_at timestamptz, created_at timestamptz not null default now());
create table if not exists kt_inks (id uuid primary key default gen_random_uuid(), post_id uuid not null references kt_posts(id) on delete cascade, user_id uuid not null references kt_users(id) on delete cascade, amount integer not null default 1 check(amount between 1 and 10), color text not null, created_at timestamptz not null default now(), unique(post_id,user_id));
create table if not exists kt_groups (id uuid primary key default gen_random_uuid(), owner_id uuid not null references kt_users(id) on delete cascade, name text not null, hashtag text unique not null, rules text not null default '', image_url text not null default '', created_at timestamptz not null default now());
create table if not exists kt_group_members (group_id uuid not null references kt_groups(id) on delete cascade, user_id uuid not null references kt_users(id) on delete cascade, primary key(group_id,user_id));
create table if not exists kt_purchases (id uuid primary key default gen_random_uuid(), user_id uuid not null references kt_users(id) on delete cascade, item text not null check(item in ('caneta','regua','selo')), cost integer not null, created_at timestamptz not null default now());
create table if not exists kt_books (id uuid primary key default gen_random_uuid(), owner_id uuid not null references kt_users(id) on delete cascade, title text not null, description text not null default '', cover_url text not null default '', published boolean not null default true, featured_until timestamptz, created_at timestamptz not null default now());
create table if not exists kt_book_posts (book_id uuid not null references kt_books(id) on delete cascade, post_id uuid not null references kt_posts(id) on delete cascade, position integer not null default 0, primary key(book_id,post_id));
create table if not exists kt_group_rules (group_id uuid primary key references kt_groups(id) on delete cascade, body text not null default '');
create index if not exists kt_books_featured on kt_books(featured_until desc);
create index if not exists kt_posts_feed on kt_posts(created_at desc);
create index if not exists kt_inks_post on kt_inks(post_id,created_at desc);
